// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TesteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void teste() {
    driver.get("http://sampleapp.tricentis.com/101/app.php");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.id("make")).click();
    {
      WebElement dropdown = driver.findElement(By.id("make"));
      dropdown.findElement(By.xpath("//option[. = 'Honda']")).click();
    }
    driver.findElement(By.id("make")).click();
    driver.findElement(By.id("engineperformance")).click();
    driver.findElement(By.id("engineperformance")).sendKeys("6");
    driver.findElement(By.id("dateofmanufacture")).click();
    driver.findElement(By.id("dateofmanufacture")).sendKeys("07/21/2021");
    driver.findElement(By.id("numberofseats")).click();
    {
      WebElement dropdown = driver.findElement(By.id("numberofseats"));
      dropdown.findElement(By.xpath("//option[. = '7']")).click();
    }
    driver.findElement(By.id("numberofseats")).click();
    driver.findElement(By.id("fuel")).click();
    {
      WebElement dropdown = driver.findElement(By.id("fuel"));
      dropdown.findElement(By.xpath("//option[. = 'Gasolina']")).click();
    }
    driver.findElement(By.id("fuel")).click();
    driver.findElement(By.id("listprice")).click();
    driver.findElement(By.id("listprice")).sendKeys("500");
    driver.findElement(By.cssSelector(".idealsteps-step:nth-child(1)")).click();
    driver.findElement(By.id("licenseplatenumber")).click();
    driver.findElement(By.id("licenseplatenumber")).sendKeys("5");
    driver.findElement(By.id("annualmileage")).click();
    driver.findElement(By.id("annualmileage")).sendKeys("100");
    driver.findElement(By.cssSelector("#nextenterinsurantdata > font > font")).click();
    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("firstname")).sendKeys("Averaldo");
    driver.findElement(By.id("lastname")).click();
    driver.findElement(By.id("lastname")).sendKeys("Jose");
    driver.findElement(By.id("birthdate")).click();
    driver.findElement(By.id("birthdate")).sendKeys("03/11/1974");
    driver.findElement(By.cssSelector(".field:nth-child(4) .ideal-radiocheck-label:nth-child(1) > font > font")).click();
    driver.findElement(By.id("streetaddress")).click();
    driver.findElement(By.id("streetaddress")).sendKeys("Rua Pedro Diaz de Oviedo, 86");
    {
      WebElement dropdown = driver.findElement(By.id("country"));
      dropdown.findElement(By.xpath("//option[. = 'Brasil']")).click();
    }
    driver.findElement(By.id("zipcode")).sendKeys("04856383");
    driver.findElement(By.id("city")).sendKeys("ADAMANTINA");
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("São Paulo");
    driver.findElement(By.id("occupation")).click();
    {
      WebElement dropdown = driver.findElement(By.id("occupation"));
      dropdown.findElement(By.xpath("//option[. = 'Empregado']")).click();
    }
    driver.findElement(By.id("occupation")).click();
    driver.findElement(By.cssSelector(".idealforms-field .ideal-radiocheck-label:nth-child(1) > font > font")).click();
    driver.findElement(By.id("picture")).click();
    driver.findElement(By.id("website")).click();
    driver.findElement(By.id("picture")).click();
    driver.findElement(By.cssSelector(".ideal-radiocheck-label:nth-child(3) > font > font")).click();
    driver.findElement(By.id("website")).click();
    driver.findElement(By.id("website")).sendKeys("https://www.google.com.br/");
    driver.findElement(By.id("picture")).click();
    driver.findElement(By.cssSelector("#nextenterproductdata > font > font")).click();
    js.executeScript("window.scrollTo(0,370)");
    driver.findElement(By.id("startdate")).click();
    driver.findElement(By.id("startdate")).sendKeys("07/21/2023");
    driver.findElement(By.id("insurancesum")).click();
    {
      WebElement dropdown = driver.findElement(By.id("insurancesum"));
      dropdown.findElement(By.xpath("//option[. = '30.000.000,00']")).click();
    }
    driver.findElement(By.id("insurancesum")).click();
    driver.findElement(By.id("meritrating")).click();
    {
      WebElement dropdown = driver.findElement(By.id("meritrating"));
      dropdown.findElement(By.xpath("//option[. = 'Malus 10']")).click();
    }
    driver.findElement(By.id("meritrating")).click();
    driver.findElement(By.id("damageinsurance")).click();
    {
      WebElement dropdown = driver.findElement(By.id("damageinsurance"));
      dropdown.findElement(By.xpath("//option[. = 'Nenhuma cobertura']")).click();
    }
    driver.findElement(By.id("damageinsurance")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".field:nth-child(5) .ideal-radiocheck-label:nth-child(1) > font > font"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".field:nth-child(5) .ideal-radiocheck-label:nth-child(1) > font > font")).click();
    driver.findElement(By.id("courtesycar")).click();
    {
      WebElement dropdown = driver.findElement(By.id("courtesycar"));
      dropdown.findElement(By.xpath("//option[. = 'Não']")).click();
    }
    driver.findElement(By.id("courtesycar")).click();
    driver.findElement(By.cssSelector("#nextselectpriceoption > font > font")).click();
    js.executeScript("window.scrollTo(0,220)");
    driver.findElement(By.cssSelector(".choosePrice:nth-child(4) > .ideal-radio")).click();
    driver.findElement(By.cssSelector("#downloadquote .fa")).click();
    js.executeScript("window.scrollTo(0,80)");
  }
}
